# tasks file for roles/folder
- name: create directory "{{ pg_data }}"
  ansible.builtin.file:
    path: "{{ pg_data }}"
    state: directory
    recurse: yes
    owner: postgres
    group: postgres
    mode: '0700'
  tags: 
    - create_directory

- name: create directory "{{ pg_wal }}"
  ansible.builtin.file:
    path: "{{ pg_wal }}"
    state: directory
    recurse: yes
    owner: postgres
    group: postgres
    mode: '0700'
  tags: 
    - create_directory

- name: Mount up device by label
  ansible.posix.mount:
    path: "{{ pg_data }}"
    src: "{{ pg_data }}"
    fstype: ext4
    state: mounted
  tags:
    - mount

- name: Mount up device by label
  ansible.posix.mount:
    path: "{{ pg_wal }}"
    src: "{{ pg_wal }}"
    fstype: ext4
    state: mounted
  tags:
    - mount

- name: chown_directory /pgsql
  ansible.builtin.file:
    path: /pgsql
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  tags: 
    - chown_directory

- name: chown_directory "{{ pg_data }}"
  ansible.builtin.file:
    path: "{{ pg_data }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  tags: 
    - chown_directory

- name: create directory "{{ pg_wal }}"
  ansible.builtin.file:
    path: "{{ pg_wal }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  tags: 
    - chown_directory